CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phone_number" varchar(15) UNIQUE NOT NULL,
  "name" varchar(100),
  "avatar_url" varchar(255),
  "bio" varchar(255),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "groups" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "description" text,
  "location" varchar(255),
  "created_by" bigint NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "group_members" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "role" varchar(50) DEFAULT 'member',
  "joined_at" timestamp DEFAULT (now())
);

CREATE TABLE "messages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "events" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" bigint NOT NULL,
  "name" varchar(100) NOT NULL,
  "description" text,
  "start_time" timestamp NOT NULL,
  "end_time" timestamp,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "event_participants" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "joined_at" timestamp DEFAULT (now())
);

ALTER TABLE "groups" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "group_members" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("id");

ALTER TABLE "group_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "events" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("id");

ALTER TABLE "event_participants" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id");

ALTER TABLE "event_participants" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
